immregistries/smm-tester

- .gitignore
- src/main/java/org/immregistries/smm/mover/SendData.java
- src/main/java/org/immregistries/smm/tester/ConnectServlet.java
- src/main/java/org/immregistries/smm/tester/connectors/Connector.java
- src/main/java/org/immregistries/smm/tester/connectors/ConnectorFactory.java
- src/main/java/org/immregistries/smm/tester/connectors/MLLPConnector.java
Please merge MLLP changes into master branch!  I believe these changes are ready.
> Josh hull/mllp protocol

- pom.xml
> updates maven-compiler with character encoding

- src/main/java/org/immregistries/smm/tester/GenerateExamplesServlet.java
- src/main/java/org/immregistries/smm/tester/ModifyMessageServlet.java
- src/main/webapp/WEB-INF/web.xml
Work I did in December to be able to generate examples. Needs to be merged in at some point. Before doing that I need to better document this so that it can be visible on Florence.
> AART-2334 Created new servlet

- src/main/java/org/immregistries/smm/transform/TestCaseMessage.java
- src/main/java/org/immregistries/smm/transform/TransformRequest.java
- src/main/java/org/immregistries/smm/transform/Transformer.java
- src/test/java/org/immregistries/smm/transform/TransformerTest.java
https://github.com/immregistries-internal/AART/issues/2486
> AART- 2486 - Set and read test case message variables to map

- src/main/java/org/immregistries/smm/tester/Authenticate.java
- src/main/java/org/immregistries/smm/transform/Transformer.java
- src/main/java/org/immregistries/smm/transform/procedure/AddVariation.java
- src/main/java/org/immregistries/smm/transform/procedure/AlternativeBeginnings.java
- src/main/java/org/immregistries/smm/transform/procedure/AlternativeEndings.java
- src/main/java/org/immregistries/smm/transform/procedure/AlternativeSpellings.java
- src/main/java/org/immregistries/smm/transform/procedure/AlternativeVowels.java
- src/main/java/org/immregistries/smm/transform/procedure/HyphenateVariation.java
- src/main/java/org/immregistries/smm/transform/procedure/ProcedureFactory.java
- src/main/java/org/immregistries/smm/transform/procedure/TextChange.java
- src/main/java/org/immregistries/smm/transform/procedure/TextTypo.java
- src/test/java/org/immregistries/smm/transform/procedure/AlternativeSpellingsTest.java
https://github.com/immregistries-internal/AART/issues/2476
> AART-2476 - Alternate Spellings

- src/main/java/org/immregistries/smm/transform/procedure/AlternativeEndingVowels.java
- src/main/java/org/immregistries/smm/transform/procedure/ProcedureFactory.java
- src/test/java/org/immregistries/smm/transform/procedure/AlternativeEndingVowelsTest.java
- src/test/java/org/immregistries/smm/transform/procedure/ProcedureCommonTest.java
https://github.com/immregistries-internal/AART/issues/2475
> AART-2475 - Alternative ending vowels

- src/main/java/org/immregistries/smm/transform/procedure/ProcedureFactory.java
- src/main/java/org/immregistries/smm/transform/procedure/SpecialCharacters.java
- src/main/java/org/immregistries/smm/transform/procedure/SpecialCharactersExtended.java
- src/test/java/org/immregistries/smm/transform/procedure/SpecialCharactersExtendedTest.java
- src/test/java/org/immregistries/smm/transform/procedure/SpecialCharactersTest.java
https://github.com/immregistries-internal/AART/issues/2478
> AART-2478 - special characters

- src/main/java/org/immregistries/smm/transform/Transformer.java
- src/test/java/org/immregistries/smm/transform/TransformerTest.java
https://github.com/immregistries-internal/AART/issues/2568
> AART-2568 - Add [SPACE] replacement

- src/main/java/org/immregistries/smm/transform/procedure/SpecialCharacters.java
- src/main/java/org/immregistries/smm/transform/procedure/SpecialCharactersExtended.java
- src/test/java/org/immregistries/smm/transform/procedure/ProcedureCommonTest.java
- src/test/java/org/immregistries/smm/transform/procedure/SpecialCharactersExtendedTest.java
- src/test/java/org/immregistries/smm/transform/procedure/SpecialCharactersTest.java
https://github.com/immregistries-internal/AART/issues/2478
> AART-2478 - Convert UTF-8 diacritics to ASCII

- src/main/java/org/immregistries/smm/transform/Transformer.java
- src/test/java/org/immregistries/smm/transform/TransformerTest.java
https://github.com/immregistries-internal/AART/issues/2499
> AART-2499 - Repeat referencing using "-?"

- src/main/java/org/immregistries/smm/transform/procedure/AlternativeEndingVowels.java
- src/main/java/org/immregistries/smm/transform/procedure/TextTypo.java
- src/test/java/org/immregistries/smm/transform/procedure/AddVariationTest.java
- src/test/java/org/immregistries/smm/transform/procedure/AddressStreetVariationTest.java
- src/test/java/org/immregistries/smm/transform/procedure/AlternativeBeginningsTest.java
- src/test/java/org/immregistries/smm/transform/procedure/AlternativeEndingVowelsTest.java
- src/test/java/org/immregistries/smm/transform/procedure/AlternativeEndingsTest.java
- src/test/java/org/immregistries/smm/transform/procedure/AlternativeSpellingsTest.java
- src/test/java/org/immregistries/smm/transform/procedure/AlternativeVowelsTest.java
- src/test/java/org/immregistries/smm/transform/procedure/FirstNameConvertNicknameTest.java
- src/test/java/org/immregistries/smm/transform/procedure/HyphenateVariationTest.java
- src/test/java/org/immregistries/smm/transform/procedure/LastNameHyphenateOrSwapTest.java
- src/test/java/org/immregistries/smm/transform/procedure/SpecialCharactersExtendedTest.java
- src/test/java/org/immregistries/smm/transform/procedure/SpecialCharactersTest.java
- src/test/java/org/immregistries/smm/transform/procedure/TextLetterToNumberTypoTest.java
- src/test/java/org/immregistries/smm/transform/procedure/TextNumberToLetterTypoTest.java
- src/test/java/org/immregistries/smm/transform/procedure/TextTypoTest.java
https://github.com/immregistries-internal/AART/issues/2605
Should handle an empty field correctly.
> AART-2605 - Handle empty string field

- src/main/java/org/immregistries/smm/transform/procedure/LastNamePrefixVariation.java
- src/main/java/org/immregistries/smm/transform/procedure/ProcedureFactory.java
- src/main/java/org/immregistries/smm/transform/procedure/RemoveLastNamePrefix.java
- src/test/java/org/immregistries/smm/transform/procedure/LastNamePrefixVariationTest.java
- src/test/java/org/immregistries/smm/transform/procedure/RemoveLastNamePrefixTest.java
https://github.com/immregistries-internal/AART/issues/2659
Also updated the wiki:
https://github.com/immregistries/smm-tester/wiki/Transform-Logic#remove-last-name-prefix
> AART-2659 - New RemoveLastNamePrefix procedure

- src/main/java/org/immregistries/smm/transform/procedure/HyphenateVariation.java
- src/test/java/org/immregistries/smm/transform/procedure/HyphenateVariationTest.java
Fixed the random value lookup, added better testing so this doesn't happen again in the future.
https://github.com/immregistries-internal/AART/issues/2655
> AART-2655 - Fix city hyphenate variation transform procedure

- src/main/java/org/immregistries/smm/transform/procedure/SuffixVariation.java
- src/test/java/org/immregistries/smm/transform/procedure/SuffixVariationTest.java
https://github.com/immregistries-internal/AART/issues/2669
> AART-2669 - Fix suffix order bug, add more suffixes

- pom.xml
- src/main/java/org/immregistries/smm/transform/Transformer.java
- src/test/java/org/immregistries/smm/transform/TransformerTest.java
https://github.com/immregistries-internal/AART/issues/3102
> AART-3102 - Special Vaccine Modifiers

- src/main/java/org/immregistries/smm/tester/SubmitServlet.java
- src/main/java/org/immregistries/smm/tester/connectors/Connector.java
- src/main/java/org/immregistries/smm/transform/Transformer.java
- src/test/java/org/immregistries/smm/tester/connectors/ConnectorTest.java
https://github.com/immregistries-internal/AART/issues/3101
> AART-3101 - Ability to apply transforms based on wildcard scenarios

- src/main/java/org/immregistries/smm/transform/procedure/AbstractSuffixVariation.java
- src/main/java/org/immregistries/smm/transform/procedure/ProcedureFactory.java
- src/main/java/org/immregistries/smm/transform/procedure/SuffixVariation.java
- src/main/java/org/immregistries/smm/transform/procedure/SuffixVariationNumbers.java
- src/main/java/org/immregistries/smm/transform/procedure/SuffixVariationPeriods.java
- src/test/java/org/immregistries/smm/transform/procedure/AbstractSuffixVariationTest.java
- src/test/java/org/immregistries/smm/transform/procedure/SuffixVariationNumbersTest.java
- src/test/java/org/immregistries/smm/transform/procedure/SuffixVariationPeriodsTest.java
- src/test/java/org/immregistries/smm/transform/procedure/SuffixVariationTest.java
https://github.com/immregistries-internal/AART/issues/3146
> AART-3146 - Break up suffix varation into three different ones

- src/main/java/org/immregistries/smm/transform/TransformRequest.java
- src/main/java/org/immregistries/smm/transform/Transformer.java
- src/test/java/org/immregistries/smm/transform/TransformerTest.java
https://github.com/immregistries-internal/AART/issues/3102
RXA fix, does NOT include order group modifications yet.
> AART-3102 - Only check special modifier for that specific RXA

- src/main/java/org/immregistries/smm/tester/manager/query/QueryConverterQBPZ34.java
https://github.com/immregistries-internal/AART/issues/3266
> AART-3266 - Set MSH-15 to "ER" for Z34

- src/main/java/org/immregistries/smm/transform/procedure/TextLetterToNumberTypo.java
Found while running unit tests for previous PR.
> Fix edge case where no letters would get converted to number

- src/main/java/org/immregistries/smm/tester/connectors/Connector.java
- src/main/java/org/immregistries/smm/transform/Transformer.java
- src/test/java/org/immregistries/smm/tester/connectors/ConnectorTest.java
https://github.com/immregistries-internal/AART/issues/3242
> AART-3242 - Negative wildcard and multiple transform scenario support
